on:
  push:
    branches: [ main ]
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v2

  check:
    if: github.event_name == 'pull_request'
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: '3.13'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
        debian-version: [ "bookworm", "trixie" ]
        target: [ "pipx" ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    permissions:
      contents: read
      packages: read
    with:
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: false
      target: ${{ matrix.target }}

  post-build-container-image:
    runs-on: ubuntu-24.04
    if: "!cancelled() && github.event_name == 'pull_request'"
    needs: build-container-image
    steps:
      - run: |
          if [ "true" == "${{ contains(needs.*.result, 'failure') }}" ]
          then
            echo "A required job failed"
            exit 1
          else
            echo "All required jobs passed"
          fi

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    with:
      build-tool: uv
      python-version: '3.13'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
        debian-version: [ "bookworm", "trixie" ]
        target: [ "pipx" ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    permissions:
      contents: read
      packages: write
    with:
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: true
      target: ${{ matrix.target }}
      version: ${{ needs.bump.outputs.version }}-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
