on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check:
    uses: BlindfoldedSurgery/actions-actions/.github/workflows/commitizen-check.yml@v2
    if: true

  build-container-image:
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v2
    with:
      push-image: ${{ false && github.ref_name == github.event.repository.default_branch }}
