on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check:
    if: github.event_name == 'pull_request'
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      python-version: '3.13'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        debian-version: [ "bullseye", "bookworm" ]
        target: [ "installer", "pipx" ]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v7
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-latest-arm64-2x' || 'ubuntu-latest' }}
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: false
      target: ${{ matrix.target }}

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    with:
      python-version: '3.13'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        debian-version: [ "bullseye", "bookworm" ]
        target: [ "installer", "pipx" ]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v7
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-latest-arm64-2x' || 'ubuntu-latest' }}
      digest-artifact-name: digests-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: true
      target: ${{ matrix.target }}
      version: ${{ needs.bump.outputs.version }}-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
      tag-suffix: -${{ matrix.platform }}

  merge-container-images:
    needs:
      - bump
      - push-container-images
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        debian-version: [ "bullseye", "bookworm" ]
        target: [ "installer", "pipx" ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/merge-manifests.yml@v7
    with:
      image-name: poetry
      tag: ${{ needs.bump.outputs.version }}-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
      variant-digests: digests-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
