on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check:
    if: github.event_name == 'pull_request'
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      python-version: '3.13'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        debian-version: [ "bullseye", "bookworm" ]
        target: [ "installer", "pipx" ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    with:
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: false
      target: ${{ matrix.target }}

  post-build-container-image:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    needs: build-container-image
    steps:
      - run: echo "All images built"

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    with:
      python-version: '3.13'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        debian-version: [ "bullseye", "bookworm" ]
        target: [ "installer", "pipx" ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    with:
      additional-build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        DEBIAN_VERSION=${{ matrix.debian-version }}
      image-name: poetry
      push-image: true
      target: ${{ matrix.target }}
      version: ${{ needs.bump.outputs.version }}-${{ matrix.target }}-${{ matrix.python-version }}-${{ matrix.debian-version }}
